### ISSUE TITLE
low_card_int, why it should be treated as both category and continuous

### ISSUE THREAD

**Issue by williamwongys** [dabl/dabl#131]
I assume low_card_int is ordinal category. It should be treated as continuous only as the order is important. I read in your codes, it is also treated as category which is subsequently encoded using one-hot. I think this should not be right as it removes the "order-ness" from the ordinal category and added performance bottleneck.

What is the rationale of treating ordinal category as both continuous and category? Is there any literature to support this implementation (I didn't manage to find any)?

**Comment by amueller** [comment]
Why is your assumption that it is an ordinal category?

This stands for "low cardinality integer". The reason I introduced this category is because it's hard for these to distinguish whether these are categorical or continuous variables. Very commonly, categorical variables are not assigned categorical dtype in pandas (for example if you just read them from a csv).

Given just the data, it's quite hard to figure out whether a variable of this type is supposed to be treated as ordinal or not. There is a ``guess_ordinal`` function in the preprocessing module right now that is used for visualization and uses the histogram of the integers to figure out if it should be treated as ordinal or not.

In the preprocessing, I'm using both encodings as that seems a safer strategy for linear models.

**Comment by williamwongys** [comment]
So for ordinal feature, I should set it as continuous in type_hints?

**Comment by amueller** [comment]
Yes. This might need better documentation. Thanks for bringing this up.

**Comment by williamwongys** [comment]
I check that your continuous variables will be standardised using StandardScaler. This will distort the equidistance relationship among the ordinal values. I would think we should use MinMaxScaler to preserve equidistance property.

**Comment by amueller** [comment]
I'm not sure I follow. Within a given feature, both preserve them being equidistant, across features, neither will.

**Comment by williamwongys** [comment]
I am sorry, I made a mistake, yes, both will preserve the equidistant property within a given feature.
