### ISSUE TITLE
AnyClassifier crashing with TypeError <' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by capt-pyro** [dabl/dabl#238]
The anyclassfier crashes when training on a dataset that has been cleaned (nan imputed or removed) externally. The datasets has categorical data, but it should be onehot encoded by Easypreprocessor. A previous run on simpleclassifier ran but when inspected, some continuous data that I had type hinted as continuous was treated as categorical (Potentially another issue).

**Comment by amueller** [comment]
Thank you for opening the issue. Can you please provide some sample data to reproduce? What version of sklearn are you using?

Thanks!

**Comment by capt-pyro** [comment]
I'm currently using scikit-learn 0.23.1 and DABL 0.1.8. I've also attached a small sample of the cleaned up data set i was working with. Provided as a CSV in a zip file. The target is "Loan Status".
[cleaned_sample_data.zip](https://github.com/dabl/dabl/files/4892474/cleaned_sample_data.zip)

**Comment by amueller** [comment]
Ah, thanks. That was an incompatible change in sklearn in the parameter :-/ ``None`` used to be supported but is not any more, I opened https://github.com/scikit-learn/scikit-learn/issues/17870

This has been fixed in the development version of dabl, so you can try using that by installing from github. However, there is some issues with the portfolio in the development version as well:
https://github.com/dabl/dabl/issues/243

(Though it should work in principle).

**Comment by amueller** [comment]
Should be fixed in #246
